# Generated by Django 6.0.3 on 2026-03-31 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0005_magictoken_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_profiles', to='rol.character'),
        ),
    ]
