# Generated by Django 6.0.3 on 2026-04-07 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rol", "0007_sesiondecronica_perfildevoz_fragmentodetranscripcion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfildevoz",
            name="character",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="voice_profiles",
                to="rol.character",
            ),
        ),
    ]
