# Generated by Django 6.0.4 on 2026-04-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rol", "0008_alter_perfildevoz_character"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="characters/avatars/"
            ),
        ),
    ]
