# Generated by hand for Phase 4

from django.db import migrations, models


def purge_sessions(apps, schema_editor):
    ChronicleSession = apps.get_model("rol", "ChronicleSession")
    TranscriptionFragment = apps.get_model("rol", "TranscriptionFragment")
    # Delete all fragments first due to FK
    TranscriptionFragment.objects.all().delete()
    # Delete all sessions
    ChronicleSession.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("rol", "0010_chroniclesession_remove_perfildevoz_character_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chroniclesession",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(purge_sessions),
    ]
